### ISSUE TITLE
Button a11y ("Next Step") buttons can not be focused

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/chooser#199]
The tool can't fully be used with keyboard access—the 'Next' buttons no not have a focus state, nor can be tabbed to.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Yashs911** [comment]
@zackkrida I would like to work on this issue.

**Comment by Yashs911** [comment]
@zackkrida Adding href="#" to all the NEXT Step links solves the problem so should I go ag=head with this solution.

**Comment by obulat** [comment]
@Yashs911 , your solution works, but I would like to rework the stepper component entirely to add it to the Vocabulary, the design system of Creative Commons, and I will add a more semantic solution for this (actually making the button a <button>), and adding the ability to tab to steps.

**Comment by Aspie96** [comment]
It alread is a tag "A", but I am not sure it is more semantic. I think a tag BUTTON might be more semantic, given that it is a button.
Also I wonder if it should actually be a form and if the button should be a submit button, both for semantic reasons and because it really should respond to "enter".

**Comment by obulat** [comment]
@Aspie96 , I have merged a PR that adds the Vocabulary button components that are actually buttons, not links. So, now a user can navigate to a radio input using <kbd>Tab</kbd>, select the necessary radio input using <kbd>Space</kbd>/arrow buttons/<kbd>Enter</kbd> , then navigate to the correct button with <kbd>Tab</kbd> and go to the next step by clicking <kbd>Enter</kbd>.

This Issue is closed by #231
