### ISSUE TITLE
Implement Tools for enhancing the code quality and developer experience.

### ISSUE THREAD

**Issue by Cronus1007** [creativecommons/chooser#293]
## Problem
The `chooser` repo lacks in various terms. Enlisting a few like 

1. CI/CD integration while formation of a pull request like TravisCI,CircleCI
2. Codecov tools like Codecov
3. Dependabot-preview  for regulating the dependencies.

## Description
The reports formed by ci/cd and codecov tools will lead to better maintenance of the repo in the long run. 
Dependabot is a widely accepted practice in majority of the open source organisation. So just a suggestion.
A need for the discussion is a high priority. 

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by obulat** [comment]
Thank you, @Cronus.  
The Chooser already has a CI/CD setup through Github actions. You can see it work in this screenshot, where one of the PRs has a red cross next to it, instead of a green tick, due to the failing tests:
![image](https://user-images.githubusercontent.com/15233243/104114378-960fa580-52b8-11eb-99a3-0211ff2e76d7.png)

Code coverage is not checked during the CI process, but we do inspect it when we run tests locally. I do not see the value for a separate tool like Codecov here.

We have previously discussed that the Dependabot has sometimes made false positive/negative PRs in other repos, so we are not going to add it here at this moment.
