### ISSUE TITLE
Shifting e2e testing from nightwatch to cypress

### ISSUE THREAD

**Issue by Cronus1007** [creativecommons/chooser#294]
## Problem and Reasons 
A suggestion from my side is that nightwatch being a powerful tool for e2e testing but when it comes to cypress it is far better than nightwatch in my opinion
The enlisted reasons are :- 
1.Since chooser is a purely vue/js based repo so cypress is highly recommended for js repos.
2. Also provides Parallel execuion while passing a --parallel flag 
3. Cross Browser Testing 
4. Much Stable 
5. Enhanced Debuggability

## Alternatives
There are many other e2e testing tools like TestCafe and various others 

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by obulat** [comment]
I support moving the e2e testing from Nightwatch to Cypress, for several reasons:

1. Stability of the tests thanks to automatic waiting. The current e2e tests in the Chooser often fail because an element is not interactable. This was made worse when we added automatic scrolling after a step is complete.
2. Debuggability of the tests.
3. Parallel execution feature.
4. Cypress is used in other CC repos.

**Comment by Cronus1007** [comment]
@obulat  Sure I will raise a PR.
