### ISSUE TITLE
Low contrast in the tabs of navigation bar

### ISSUE THREAD

**Issue by yaduu572** [creativecommons/chooser#306]
The color scheme of tabs in the navigation bar does not pass the sufficient criteria as visible in lightHouse criteria of inspect.
As you can in the below image, the color contrast is less as compared to the required one in chrome.
![image](https://user-images.githubusercontent.com/53738878/104842789-0f2c7f80-58ed-11eb-888e-111715611d49.png)

**Comment by obulat** [comment]
Thank you for raising this issue, @yaduu572 !
@panchovm , even after making the tomato color darker, the breadcrumb element does not pass contrast a11y requirements because for smaller texts contrast needs to be higher. What is the best thing to do here?

**Comment by panchovm** [comment]
Are we talking of tomato (`#C74200`) over lightergray (`#f5f5f5`)? I checked the contrast and it meets the AA level for normal and large sizes. Can you give me more details?

**Comment by obulat** [comment]
Oh, sorry, @panchovm , there is a mix up on the Chooser web site: the help links have been changed to `#c74200`, but the breadcrumbs are still the previous tomato color. This will be changed as soon as we release the new Vocabulary version.

You are right, the new tomato color passes AA levels for normal text (although it fails the AAA levels):
![image](https://user-images.githubusercontent.com/15233243/104924748-b8f22780-5952-11eb-9092-83b9e45d8a1d.png)

I will close this issue because the solution has already been merged, it just needs a new release.
