### ISSUE TITLE
Adding keyboard navigation functionality.

### ISSUE THREAD

**Issue by ashu54-aseem** [creativecommons/chooser#307]
At present, Chooser does not support navigating through the steps via keyboard. Hence to improve the accessibility, a simple functionality of triggering events of "Back" and "Next" buttons on keystrokes (probably with arrow keys or enter key) can be added.

**Comment by obulat** [comment]
Could you explain exactly the keyboard navigation functionality you expect, @ashu54-aseem ?

Currently, you can navigate to the first step using a <kbd>Tab</kbd> key. With the focus inside the step, you can select a radio input using the <kbd>Space</kbd> or the <kbd>Enter</kbd> keys. Then you can again use the <kbd>Tab</kbd> key to navigate to the `Next` button, and use <kbd>Enter</kbd> key to go to the next step. 

When you want to go to the previous step, you can use <kbd>Shift</kbd>+<kbd>Tab</kbd>.

**Comment by ashu54-aseem** [comment]
My idea was to reduce the number of keystrokes involved in the steps and rather use left and right keys to go to the next or previous step as I think would be more intuitive (perhaps also adding a little tip at the top or side to let the user know) due to the reduced amount of keystrokes.

**Comment by obulat** [comment]
I will discuss your suggestion with other members of the CC community.

However, my opinion on this is that using arrow keys<kbd>🠖</kbd> or <kbd>🠔</kbd> in this way (when the step is focused, i.e. when a radio group is focused) would interfere with the established UX pattern: when a radio input is focused, the left and up arrows move the focus to the previous radio input and select it, and the right and down arrow move the focus to the next radio input and select it. You can read more about it on [w3.org](https://www.w3.org/TR/wai-aria-practices/#radiobutton).
 In addition, because the stepper is vertical, I would think that using horizontal buttons to advance the step would be counter-intuitive.

**Comment by Cronus1007** [comment]
@obulat Any updates regarding this issue.

**Comment by zackkrida** [comment]
Hi @ashu54-aseem an important part of web accessibility is following established patterns of user behavior. The arrow key functionality you've described sounds nice in theory, but isn't common enough for us to consider in this project.

Thank you for your suggestion, but we are going to keep the existing keyboard navigation behavior.
