### ISSUE TITLE
Enhancing the CI CD with Netlify Deploy Support

### ISSUE THREAD

**Issue by Cronus1007** [creativecommons/chooser#332]
## Problem and Solution
Currently for the `CI CD` builds the repository is mainly focussed upon the `Github Pages`. We can also provide a support for the `Netlify` Deploys as  done in the `Vocabulary` repository. With netlify deploy the `deploy-preview` will be with great ease. 

## Additional context

![Screenshot from 2021-02-26 17-38-24](https://user-images.githubusercontent.com/56436023/109298350-71b45c00-7859-11eb-87ef-caacf26c1897.png)

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
Hi Cronus, I don't see a reason to host this on Netlify instead of GitHub pages. GitHub pages meets all of our requirements, and while it would be nice to have preview deploys for pull requests, this project intends to be rather stable, not with frequent updates. 

Perhaps we can revisit this in the future but for now I'm going to close it. Thank you!
