### ISSUE TITLE
Publish initial release of Chooser project

### ISSUE THREAD

**Issue by brylie** [creativecommons/chooser#366]
## Problem
Now that the Chooser project is fairly stable, we can publish an initial release. Publishing a release should make it easier to integrate the Chooser into downstream projects.

## Description
Publish the `0.1.0` release for the Chooser project.

## Further context

We want to publish the Chooser project as a library.

- https://cli.vuejs.org/guide/build-targets.html#library

**Comment by brylie** [comment]
@shailee-m, would you like to try and build the Chooser project as a library?

**Comment by shailee-m** [comment]
@brylie Yes, absolutely

**Comment by brylie** [comment]
OK, thanks. I'll assign you here. Let me know how the initial experiment with building the Chooser library goes. Then, we will test out using the Chooser library in a Gutenberg page.

**Comment by shailee-m** [comment]
@brylie there are some changes I would need to make to the repo's main.js file in order to wrap it into a web component. Should I update the code directly or should I create env-var. And depending on that environment variable value it will either mount for serving as a web app or as a web component??
