### ISSUE TITLE
[Feature] Export LICENSE as image (png/jpeg/webp) or SVG

### ISSUE THREAD

**Issue by Neilblaze** [creativecommons/chooser#450]
## Problem ❓
Currently, there is no option to export the generated **LICENSE** in **image format** i.e. `png`, `jpeg`, or `webp` or **SVG**. Enabling this feature will provide numerous benefits in terms of flexibility, accessibility, and enhancement of user experience, benefiting both existing and potential users.

Additionally, users can choose whether they want to export the image or copy the same to the clipboard.

![image](https://user-images.githubusercontent.com/48355572/221363743-836e33e0-a4d9-4d91-99e8-9739af413e13.png)

## Description ✨

- **Easy Sharing:** Users can easily share their license with others via email, social media, or any other platform that supports image sharing.
- **Easy Printing:** Users can print their license easily from any device or platform that supports image printing.
- **Increased Security:** Exporting the license as an image can increase security, as the license can be saved as a password-protected or encrypted image file, making it harder for unauthorized users to access it.
- **Compatibility:** Image formats are widely supported across devices and platforms, so exporting licenses as images can ensure that users can easily access and share their licenses across a range of devices and platforms.
- **Customization:** Users can customize the image format of the license to suit their needs, such as changing the image resolution or aspect ratio to fit a specific device or platform. (Future Goals)
- **Improved Aesthetics:** Exporting the license as an image can allow users to create visually appealing designs and layouts for their license, making it more appealing to look at and easier to read.
- **Proof of Ownership:** Exporting the license as an image can provide users with a visual proof of ownership, which can be used for legal or contractual purposes.
- **Offline Access:** Users can access their license even when they are offline, as image files can be stored locally on the device and accessed without an internet connection.
- **Easy Backup:** Exporting the license as an image can provide users with an easy way to create backup of their LICENSE, as image files can be saved to cloud storage or other backup locations for safekeeping.
- **Branding:** Users can add their own branding elements to the LICENSE image, such as logos or watermarks, to personalize it and make it more professional-looking. (Future Goals)

## Implementation

- [x] I would be interested in implementing this feature.

cc: @TimidRobot, @brylie, @possumbilities

**Comment by possumbilities** [comment]
@Neilblaze Hi! and thank you for your enthusiasm ❤️ 

After thinking on it I'm not sure this is inline with the current direction or scope of the Chooser. 

- Embedding the license info into a graphic would inherently make it less Accessible, since embedding text within an image is generally not the best approach for appropriate levels of Accessibility.
- There would be no reason to password protect the license in any way, that's mostly antithetical to the purpose of Creative Commons licenses.
- Text is more widely supported than images and in many cases offers better uses for space and performance reasons. 
- Additionally, there are a lot of considerations about the CC badges and icons that users should not be manipulating in conjunction with their own branding.

Overall, I appreciate the depth of your proposal, but it definitely seems to be not within the scope of the intention of this project and the services it seeks to provide users.

I'd encourage you to keep contributing, even if this idea didn't make it through :)

Closing as not planned.
